# Generated by Django 5.2.5 on 2025-09-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('sub_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score_percentage', models.FloatField()),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'db_table': 'quiz_results',
                'ordering': ['-date_taken'],
            },
        ),
    ]
