# Generated by Django 5.2.5 on 2025-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='questions_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
