# Generated by Django 5.2.5 on 2025-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='mcq',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['topic', 'sub_topic', 'difficulty_level'], name='ui_mcq_topic_6c59a1_idx'),
        ),
    ]
