# Generated by Django 5.2.5 on 2025-09-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_mcq_difficulty_level_mcq_sub_topic_mcq_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
